version: '3.9'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    networks:
      - backend-network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001" 
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge