// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/register": {
            "post": {
                "description": "Create a new user and return JWT token upon success",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Register new user and return authentication token",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or registration failure",
                        "schema": {
                            "$ref": "#/definitions/exception.Response"
                        }
                    },
                    "500": {
                        "description": "Cannot register or token generation failure",
                        "schema": {
                            "$ref": "#/definitions/exception.Response"
                        }
                    }
                }
            }
        },
        "/validate-registration": {
            "post": {
                "description": "Check if the email already exists and whether password matches confirm password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Validate email availability and password confirmation",
                "parameters": [
                    {
                        "description": "User email and password info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserEmailInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request or password mismatch",
                        "schema": {
                            "$ref": "#/definitions/exception.Response"
                        }
                    },
                    "409": {
                        "description": "Email already exists",
                        "schema": {
                            "$ref": "#/definitions/exception.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/exception.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.UserAddress": {
            "type": "object",
            "required": [
                "country",
                "district",
                "house_number",
                "province",
                "sub_district",
                "zip_code"
            ],
            "properties": {
                "country": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "house_number": {
                    "type": "string"
                },
                "moo": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "road": {
                    "type": "string"
                },
                "soi": {
                    "type": "string"
                },
                "sub_district": {
                    "type": "string"
                },
                "zip_code": {
                    "type": "string"
                }
            }
        },
        "dto.UserEmailInfo": {
            "type": "object",
            "required": [
                "confirm_password",
                "email",
                "password"
            ],
            "properties": {
                "confirm_password": {
                    "type": "string",
                    "maxLength": 100
                },
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "password": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.UserInformation": {
            "type": "object",
            "required": [
                "address",
                "first_name",
                "last_name",
                "tel",
                "user_id"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/dto.UserAddress"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 100
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 100
                },
                "tel": {
                    "type": "string",
                    "maxLength": 10
                },
                "user_id": {
                    "type": "string",
                    "maxLength": 13
                }
            }
        },
        "dto.UserRegisterRequest": {
            "type": "object",
            "required": [
                "address",
                "email_info",
                "information"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/dto.UserAddress"
                },
                "email_info": {
                    "$ref": "#/definitions/dto.UserEmailInfo"
                },
                "information": {
                    "$ref": "#/definitions/dto.UserInformation"
                }
            }
        },
        "exception.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        },
        "model.RegisterResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
